import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import './globals.css';

import { Toaster } from '@/components/ui/toaster';
import { CypressProvider } from '@/lib/context/cypress/CypressProvider';
import { SocketProvider } from '@/lib/context/sockets/SocketProvider';
import { AuthUserProvider } from '@/lib/context/supabase/user/AuthUserProvider';
import { ThemeProvider } from '@/lib/providers/next-theme-provider';
import db from '@/lib/supabase/db';

const inter = DM_Sans({ subsets: ['latin'] });
db;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge('bg-background', inter.className)}>
        {/* enableSystem by library */}
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <CypressProvider>
            <AuthUserProvider>
              <SocketProvider>
                {children}
                <Toaster />
              </SocketProvider>
            </AuthUserProvider>
          </CypressProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
